dataset:
  name: airway
  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/SAN/medic/PerceptronHead/data/airway'
  data_format: 'nii'

logger:
  tag: '3d_airway_448_w12'

seed: 1024

model:
  name: u-net
  use_3d: 1
  input_dim: 1
  output_dim: 2
  width: 12

train:
  optimizer:
    weight_decay: 0.0005
  lr: 0.0003
  iterations: 31437
  stop_iteration: 31437
  batch: 1
  save_ema_start: 30437
  temp: 1.0
  patience: 10000
  contrast: True
  crop_aug: True
  gaussian: True
  new_size: 448
  batch_u: 0 # this has to be zero in supervised setting
  mu: 0.5
  alpha: 1.0
  warmup: 100
  warmup_start: 0

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

eval:
  batch: 1






