dataset:
  name: lungcancer
  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/home/moucheng/projects_data/Task06_Lung'
  data_format: 'nii'

logger:
  tag: 'exp1'

seed: 1024

model:
  name: u-net
  use_3d: 1
  input_dim: 1
  output_dim: 1
  width: 4
  depth: 4

train:
  transpose_dim: 1
  optimizer:
    weight_decay: 0.0005
  lr: 0.0003
  iterations: 20000
  batch: 2
  temp: 1.0
  contrast: True
  crop_aug: True
  gaussian: True
  new_size_d: 64
  new_size_w: 420
  new_size_h: 420
  batch_u: 2 # this has to be zero in supervised setting
  mu: 0.5
  learn_threshold: 1 # 0 for using fixed mu, 1 for using mu as a prior
  threshold_flag: 1 # 0 for the original implementation, 1 for new lazy implementation
  alpha: 1.0
  warmup: 0.2
  warmup_start: 0.0

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

eval:
  batch: 1






