name: ppfe-segmentation-supervised-type3-local

dataset:
  name: ppfe
  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/SAN/medic/PerceptronHead/data/ppfe/res128_type3'
  data_format: 'np'

model:
  name: u-net
  use_3d: 1
  input_dim: 1
  output_dim: 2
  width: 8

train:
  optimizer:
    weight_decay: 0.0005
  lr: 0.0003
  iterations: 14500
  stop_iteration: 14500
  batch: 2
  save_ema_start: 1450 # 10 epochs
  patience: 10000
  temp: 1.0
  contrast: True
  crop_aug: False
  gaussian: True
  batch_u: 0 # this has to be zero in supervised setting
  mu: 0.5
  alpha: 1.0
  warmup: 100

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

eval:
  optimizer:
    weight_decay: 0
  batch: 1

logger:
  tag: '3d_ppfe_sup_binary_res128_new'

seed: 1024




